export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/x-icon"
          href="/frontend_assets/img/favicon.png"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
